//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Battlefeild.rc
//
#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_BATTLEFEILD_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_BATTLEFEILD20			107
#define IDI_SMALL				108
#define IDC_BATTLEFEILD20			109
#define IDM_INSTRUCTIONS		110
#define IDD_INSTRUCTIONBOX		111

#define IDC_MYICON				2
//Show player areas menu
#define IDM_SHOWPLAYERAREAS 1101
#define IDM_HIDEPLAYERAREAS 1102
//landery list of mideval ids
#define IDD_CATAPULTBOX							301
#define IDD_CATAPULTBOX_HORSE					302
#define IDD_SOLDIERBOX_BA_HORSE_TORCH_ARMOR		303
#define IDD_SOLDIERBOX_BA_HORSE_TORCH			304
#define IDD_SOLDIERBOX_BA_HORSE_ARMOR			305
#define IDD_SOLDIERBOX_BA_HORSE					306
#define IDD_SOLDIERBOX_BA_TORCH_ARMOR			307
#define IDD_SOLDIERBOX_BA_TORCH					308
#define IDD_SOLDIERBOX_BA_ARMOR					309
#define IDD_SOLDIERBOX_BA						310
#define IDD_SOLDIERBOX_HORSE_TORCH_ARMOR		311
#define IDD_SOLDIERBOX_HORSE_TORCH				312
#define IDD_SOLDIERBOX_HORSE_ARMOR				313
#define IDD_SOLDIERBOX_HORSE					314
#define IDD_SOLDIERBOX_TORCH_ARMOR				315
#define IDD_SOLDIERBOX_TORCH					316
#define IDD_SOLDIERBOX_ARMOR					317
#define IDD_SOLDIERBOX							318
#define IDD_TORCHBOX			319
#define IDD_HORSEBOX			320
#define IDD_BA_BOX				321
#define IDD_ARMORBOX			322
#define IDD_SFARMBOX			323
#define IDD_LFARMBOX			324
#define IDD_TCENTERBOX			325
#define IDD_CATFACTORYBOX		326
#define IDD_BA_FACTORYBOX		327
#define IDD_ARMORYBOX			328
#define IDD_STABLEBOX			329
#define IDD_WALLBOX				330
#define IDD_TORCHFACTBOX		331

#define IDD_MONEYINFOBOX		332
#define IDD_TURNINFOBOX			333

#define IDM_TORCHFACTBOX		136
#define IDM_CATAPULTBOX			137
#define IDM_SOLDIERBOX			138
#define IDM_TORCHBOX			139
#define IDM_HORSEBOX			140
#define IDM_BA_BOX				141
#define IDM_ARMORBOX			142
#define IDM_SFARMBOX			143
#define IDM_LFARMBOX			144
#define IDM_TCENTERBOX			145
#define IDM_CATFACTORYBOX		146
#define IDM_BA_FACTORYBOX		147
#define IDM_ARMORYBOX			148
#define IDM_STABLEBOX			149
#define IDM_WALLBOX				150

#define IDD_SOLDIERBUYER		153
#define IDD_CATAPULTBUYER		164
#define IDD_SOLDIERSELECTION	151
#define IDD_CATAPULTSELECTION	152
#define IDD_BULLDOZER			165
// definitions for message box handlers
//make sure not to change these. If you do, everything will go wrong!
#define IDBUYHORSE				114
#define IDBUYARMOR				115
#define IDBUYTORCH				116
#define IDBUYBA					117

#define IDSOLDIER1				154
#define IDSOLDIER2				155
#define IDSOLDIER3				156
#define IDSOLDIER4				157
#define IDSOLDIER5				158
#define IDSOLDIER6				159
#define IDSOLDIER7				160
#define IDSOLDIER8				161
#define IDSOLDIER9				162
#define IDSOLDIER10				163

//define save stuff
#define IDM_SAVESLOT1			210
#define IDM_SAVESLOT2			211
#define IDM_SAVESLOT3			212
#define IDM_LOADAUTOSAVE		213
#define IDM_LOADSLOT1			214
#define IDM_LOADSLOT2			215
#define IDM_LOADSLOT3			216
#define IDM_CLEARGAME			217

#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		500
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
